package com.adk.weatherwrapper.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import com.adk.blog.errorhandling.ApiError;
import com.adk.weatherwrapper.model.OutputSection;
import com.adk.weatherwrapper.model.WeatherResponse;
import com.adk.weatherwrapper.service.VisualCrossingWeatherService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

/**
 * Controller that contains end points for access a locations weather on a specified date
 * Program Goals/Limitations:
 * Can edit location, data range, units, 
 * daily, current, or hourly
 */
@RestController
public class WeatherController {
	
	@Autowired
	private VisualCrossingWeatherService visualCrossingWeatherService;
	
	@Operation(summary = "Get the hourly data", description = "Get the hourly data for a location on a specified date range", responses = {
			@ApiResponse(description = "Success", responseCode = "200", content = @Content(schema = @Schema(implementation = WeatherResponse.class), examples = {
					@ExampleObject(value = "{\r\n"
							+ "    \"resolvedAddress\": null,\r\n"
							+ "    \"address\": \"Lima, OH\",\r\n"
							+ "    \"timezone\": \"America/New_York\",\r\n"
							+ "    \"days\": [\r\n"
							+ "        {\r\n"
							+ "            \"datetime\": \"2024-11-23\",\r\n"
							+ "            \"datetimeEpoch\": 1732338000,\r\n"
							+ "            \"tempmax\": 44.2,\r\n"
							+ "            \"tempmin\": 37.3,\r\n"
							+ "            \"temp\": 41.2,\r\n"
							+ "            \"feelslikemax\": 38.9,\r\n"
							+ "            \"feelslikemin\": 31.9,\r\n"
							+ "            \"feelslike\": 34.9,\r\n"
							+ "            \"dew\": 37.4,\r\n"
							+ "            \"humidity\": 86.2,\r\n"
							+ "            \"precip\": 0.0,\r\n"
							+ "            \"precipprob\": 0.0,\r\n"
							+ "            \"precipcover\": 0.0,\r\n"
							+ "            \"preciptype\": null,\r\n"
							+ "            \"now\": 0.0,\r\n"
							+ "            \"windgust\": 23.0,\r\n"
							+ "            \"windspeed\": 13.8,\r\n"
							+ "            \"winddir\": 283.8,\r\n"
							+ "            \"pressure\": 1015.4,\r\n"
							+ "            \"cloudcover\": 87.2,\r\n"
							+ "            \"visibility\": 9.6,\r\n"
							+ "            \"solarradiation\": 31.5,\r\n"
							+ "            \"solarenergy\": 2.7,\r\n"
							+ "            \"uvindex\": 2.0,\r\n"
							+ "            \"severerisk\": 10.0,\r\n"
							+ "            \"sunrise\": \"07:33:18\",\r\n"
							+ "            \"sunsetEpoch\": 0,\r\n"
							+ "            \"moonphase\": 0.75,\r\n"
							+ "            \"conditions\": \"Partially cloudy\",\r\n"
							+ "            \"description\": \"Partly cloudy throughout the day.\",\r\n"
							+ "            \"icon\": \"partly-cloudy-day\",\r\n"
							+ "            \"hours\": [\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"00:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 43.0,\r\n"
							+ "                    \"feelslike\": 36.1,\r\n"
							+ "                    \"humidity\": 82.66,\r\n"
							+ "                    \"dew\": 38.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 21.9,\r\n"
							+ "                    \"windspeed\": 13.8,\r\n"
							+ "                    \"winddir\": 310.0,\r\n"
							+ "                    \"pressure\": 1011.5,\r\n"
							+ "                    \"visibility\": 9.8,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"01:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 43.1,\r\n"
							+ "                    \"feelslike\": 36.2,\r\n"
							+ "                    \"humidity\": 79.79,\r\n"
							+ "                    \"dew\": 37.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 21.9,\r\n"
							+ "                    \"windspeed\": 13.8,\r\n"
							+ "                    \"winddir\": 301.0,\r\n"
							+ "                    \"pressure\": 1011.9,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"02:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 42.3,\r\n"
							+ "                    \"feelslike\": 36.3,\r\n"
							+ "                    \"humidity\": 87.89,\r\n"
							+ "                    \"dew\": 38.9,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.3,\r\n"
							+ "                    \"windspeed\": 10.4,\r\n"
							+ "                    \"winddir\": 301.0,\r\n"
							+ "                    \"pressure\": 1011.8,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"03:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 42.2,\r\n"
							+ "                    \"feelslike\": 35.4,\r\n"
							+ "                    \"humidity\": 88.05,\r\n"
							+ "                    \"dew\": 38.9,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 21.9,\r\n"
							+ "                    \"windspeed\": 12.8,\r\n"
							+ "                    \"winddir\": 300.0,\r\n"
							+ "                    \"pressure\": 1012.6,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"04:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 42.2,\r\n"
							+ "                    \"feelslike\": 35.4,\r\n"
							+ "                    \"humidity\": 85.43,\r\n"
							+ "                    \"dew\": 38.2,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 18.4,\r\n"
							+ "                    \"windspeed\": 12.8,\r\n"
							+ "                    \"winddir\": 310.0,\r\n"
							+ "                    \"pressure\": 1012.1,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Partially cloudy\",\r\n"
							+ "                    \"icon\": \"partly-cloudy-night\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"05:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 41.0,\r\n"
							+ "                    \"feelslike\": 34.4,\r\n"
							+ "                    \"humidity\": 86.32,\r\n"
							+ "                    \"dew\": 37.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 20.9,\r\n"
							+ "                    \"windspeed\": 11.4,\r\n"
							+ "                    \"winddir\": 300.0,\r\n"
							+ "                    \"pressure\": 1013.4,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"06:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.1,\r\n"
							+ "                    \"feelslike\": 33.4,\r\n"
							+ "                    \"humidity\": 89.06,\r\n"
							+ "                    \"dew\": 36.2,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.2,\r\n"
							+ "                    \"windspeed\": 8.3,\r\n"
							+ "                    \"winddir\": 301.0,\r\n"
							+ "                    \"pressure\": 1014.0,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Clear\",\r\n"
							+ "                    \"icon\": \"clear-night\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"07:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 37.3,\r\n"
							+ "                    \"feelslike\": 32.6,\r\n"
							+ "                    \"humidity\": 92.15,\r\n"
							+ "                    \"dew\": 35.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 19.5,\r\n"
							+ "                    \"windspeed\": 6.0,\r\n"
							+ "                    \"winddir\": 281.0,\r\n"
							+ "                    \"pressure\": 1014.7,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Clear\",\r\n"
							+ "                    \"icon\": \"clear-night\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"08:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.0,\r\n"
							+ "                    \"feelslike\": 34.6,\r\n"
							+ "                    \"humidity\": 89.25,\r\n"
							+ "                    \"dew\": 36.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 19.5,\r\n"
							+ "                    \"windspeed\": 6.0,\r\n"
							+ "                    \"winddir\": 300.0,\r\n"
							+ "                    \"pressure\": 1015.1,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 29.0,\r\n"
							+ "                    \"solarenergy\": 0.1,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Clear\",\r\n"
							+ "                    \"icon\": \"clear-day\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"09:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 41.0,\r\n"
							+ "                    \"feelslike\": 34.8,\r\n"
							+ "                    \"humidity\": 89.25,\r\n"
							+ "                    \"dew\": 38.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.2,\r\n"
							+ "                    \"windspeed\": 10.2,\r\n"
							+ "                    \"winddir\": 300.0,\r\n"
							+ "                    \"pressure\": 1016.1,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 85.0,\r\n"
							+ "                    \"solarenergy\": 0.3,\r\n"
							+ "                    \"uvindex\": 1.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"10:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 43.1,\r\n"
							+ "                    \"feelslike\": 36.9,\r\n"
							+ "                    \"humidity\": 82.5,\r\n"
							+ "                    \"dew\": 38.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 16.1,\r\n"
							+ "                    \"windspeed\": 11.4,\r\n"
							+ "                    \"winddir\": 310.0,\r\n"
							+ "                    \"pressure\": 1016.5,\r\n"
							+ "                    \"visibility\": 9.7,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 156.0,\r\n"
							+ "                    \"solarenergy\": 0.6,\r\n"
							+ "                    \"uvindex\": 2.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"11:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 43.1,\r\n"
							+ "                    \"feelslike\": 38.9,\r\n"
							+ "                    \"humidity\": 91.74,\r\n"
							+ "                    \"dew\": 40.9,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 16.1,\r\n"
							+ "                    \"windspeed\": 7.1,\r\n"
							+ "                    \"winddir\": 310.0,\r\n"
							+ "                    \"pressure\": 1016.6,\r\n"
							+ "                    \"visibility\": 3.2,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 121.0,\r\n"
							+ "                    \"solarenergy\": 0.4,\r\n"
							+ "                    \"uvindex\": 1.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"12:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 44.2,\r\n"
							+ "                    \"feelslike\": 38.3,\r\n"
							+ "                    \"humidity\": 84.7,\r\n"
							+ "                    \"dew\": 39.9,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 18.3,\r\n"
							+ "                    \"windspeed\": 11.3,\r\n"
							+ "                    \"winddir\": 272.0,\r\n"
							+ "                    \"pressure\": 1016.6,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 148.0,\r\n"
							+ "                    \"solarenergy\": 0.5,\r\n"
							+ "                    \"uvindex\": 1.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"13:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 44.2,\r\n"
							+ "                    \"feelslike\": 37.9,\r\n"
							+ "                    \"humidity\": 81.86,\r\n"
							+ "                    \"dew\": 39.0,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.2,\r\n"
							+ "                    \"windspeed\": 12.6,\r\n"
							+ "                    \"winddir\": 271.0,\r\n"
							+ "                    \"pressure\": 1016.6,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 79.0,\r\n"
							+ "                    \"solarenergy\": 0.3,\r\n"
							+ "                    \"uvindex\": 1.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"14:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 44.2,\r\n"
							+ "                    \"feelslike\": 38.3,\r\n"
							+ "                    \"humidity\": 79.18,\r\n"
							+ "                    \"dew\": 38.2,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 22.0,\r\n"
							+ "                    \"windspeed\": 11.5,\r\n"
							+ "                    \"winddir\": 271.0,\r\n"
							+ "                    \"pressure\": 1016.3,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 76.0,\r\n"
							+ "                    \"solarenergy\": 0.3,\r\n"
							+ "                    \"uvindex\": 1.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"15:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 42.3,\r\n"
							+ "                    \"feelslike\": 36.7,\r\n"
							+ "                    \"humidity\": 84.98,\r\n"
							+ "                    \"dew\": 38.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 23.0,\r\n"
							+ "                    \"windspeed\": 9.5,\r\n"
							+ "                    \"winddir\": 271.0,\r\n"
							+ "                    \"pressure\": 1016.1,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 39.0,\r\n"
							+ "                    \"solarenergy\": 0.1,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"16:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 41.1,\r\n"
							+ "                    \"feelslike\": 33.6,\r\n"
							+ "                    \"humidity\": 86.22,\r\n"
							+ "                    \"dew\": 37.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 20.7,\r\n"
							+ "                    \"windspeed\": 13.7,\r\n"
							+ "                    \"winddir\": 270.0,\r\n"
							+ "                    \"pressure\": 1016.5,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 18.0,\r\n"
							+ "                    \"solarenergy\": 0.1,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"17:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 40.0,\r\n"
							+ "                    \"feelslike\": 33.5,\r\n"
							+ "                    \"humidity\": 89.72,\r\n"
							+ "                    \"dew\": 37.2,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.2,\r\n"
							+ "                    \"windspeed\": 10.4,\r\n"
							+ "                    \"winddir\": 260.0,\r\n"
							+ "                    \"pressure\": 1016.3,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 5.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"18:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 40.0,\r\n"
							+ "                    \"feelslike\": 33.0,\r\n"
							+ "                    \"humidity\": 86.26,\r\n"
							+ "                    \"dew\": 36.2,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 17.2,\r\n"
							+ "                    \"windspeed\": 11.5,\r\n"
							+ "                    \"winddir\": 270.0,\r\n"
							+ "                    \"pressure\": 1017.1,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"19:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.9,\r\n"
							+ "                    \"feelslike\": 32.5,\r\n"
							+ "                    \"humidity\": 86.1,\r\n"
							+ "                    \"dew\": 36.1,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 20.7,\r\n"
							+ "                    \"windspeed\": 12.7,\r\n"
							+ "                    \"winddir\": 270.0,\r\n"
							+ "                    \"pressure\": 1017.4,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"20:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.0,\r\n"
							+ "                    \"feelslike\": 31.9,\r\n"
							+ "                    \"humidity\": 86.31,\r\n"
							+ "                    \"dew\": 35.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 15.0,\r\n"
							+ "                    \"windspeed\": 11.3,\r\n"
							+ "                    \"winddir\": 270.0,\r\n"
							+ "                    \"pressure\": 1017.8,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"21:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.0,\r\n"
							+ "                    \"feelslike\": 32.3,\r\n"
							+ "                    \"humidity\": 86.29,\r\n"
							+ "                    \"dew\": 35.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 13.9,\r\n"
							+ "                    \"windspeed\": 10.2,\r\n"
							+ "                    \"winddir\": 250.0,\r\n"
							+ "                    \"pressure\": 1017.7,\r\n"
							+ "                    \"visibility\": 9.8,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"22:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.0,\r\n"
							+ "                    \"feelslike\": 32.3,\r\n"
							+ "                    \"humidity\": 86.21,\r\n"
							+ "                    \"dew\": 35.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 12.8,\r\n"
							+ "                    \"windspeed\": 10.2,\r\n"
							+ "                    \"winddir\": 250.0,\r\n"
							+ "                    \"pressure\": 1017.2,\r\n"
							+ "                    \"visibility\": 9.9,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                },\r\n"
							+ "                {\r\n"
							+ "                    \"datetime\": \"23:00:00\",\r\n"
							+ "                    \"dateTimeEpoch\": 0,\r\n"
							+ "                    \"temp\": 39.0,\r\n"
							+ "                    \"feelslike\": 32.8,\r\n"
							+ "                    \"humidity\": 86.32,\r\n"
							+ "                    \"dew\": 35.3,\r\n"
							+ "                    \"precip\": 0.0,\r\n"
							+ "                    \"precipprob\": 0.0,\r\n"
							+ "                    \"snow\": 0.0,\r\n"
							+ "                    \"snowdepth\": 0.0,\r\n"
							+ "                    \"preciptype\": null,\r\n"
							+ "                    \"windgust\": 11.4,\r\n"
							+ "                    \"windspeed\": 9.1,\r\n"
							+ "                    \"winddir\": 260.0,\r\n"
							+ "                    \"pressure\": 1017.4,\r\n"
							+ "                    \"visibility\": 9.8,\r\n"
							+ "                    \"cloudCover\": 0.0,\r\n"
							+ "                    \"solarradiation\": 0.0,\r\n"
							+ "                    \"solarenergy\": 0.0,\r\n"
							+ "                    \"uvindex\": 0.0,\r\n"
							+ "                    \"severerisk\": 10.0,\r\n"
							+ "                    \"conditions\": \"Overcast\",\r\n"
							+ "                    \"icon\": \"cloudy\"\r\n"
							+ "                }\r\n"
							+ "            ]\r\n"
							+ "        }\r\n"
							+ "    ]\r\n"
							+ "}") })) })
	@GetMapping("/hourly/{city}/{state}/{startDate}/{endDate}")
	public ResponseEntity<Object> getHourlyWeather(@PathVariable String city, @PathVariable String state, @PathVariable String startDate, @PathVariable String endDate) throws Exception{
		return new ResponseEntity<>(visualCrossingWeatherService.makeApiCall(OutputSection.HOURLY, city, state, startDate, endDate), HttpStatus.OK);
	}
	
	@Operation(summary = "Get the Daily weather data", description = "Get the Daily weather data for a specified location in a given date range", responses = {
			@ApiResponse(description = "Success", responseCode = "200", content = @Content(schema = @Schema(implementation = WeatherResponse.class), examples = {
					@ExampleObject(value = "{\r\n"
							+ "    \"resolvedAddress\": null,\r\n"
							+ "    \"address\": \"Lima, OH\",\r\n"
							+ "    \"timezone\": \"America/New_York\",\r\n"
							+ "    \"days\": [\r\n"
							+ "        {\r\n"
							+ "            \"datetime\": \"2024-11-24\",\r\n"
							+ "            \"datetimeEpoch\": 1732424400,\r\n"
							+ "            \"tempmax\": 49.0,\r\n"
							+ "            \"tempmin\": 37.2,\r\n"
							+ "            \"temp\": 41.1,\r\n"
							+ "            \"feelslikemax\": 46.0,\r\n"
							+ "            \"feelslikemin\": 30.1,\r\n"
							+ "            \"feelslike\": 35.9,\r\n"
							+ "            \"dew\": 35.3,\r\n"
							+ "            \"humidity\": 80.2,\r\n"
							+ "            \"precip\": 0.0,\r\n"
							+ "            \"precipprob\": 3.0,\r\n"
							+ "            \"precipcover\": 0.0,\r\n"
							+ "            \"preciptype\": null,\r\n"
							+ "            \"now\": 0.0,\r\n"
							+ "            \"windgust\": 18.3,\r\n"
							+ "            \"windspeed\": 10.3,\r\n"
							+ "            \"winddir\": 207.2,\r\n"
							+ "            \"pressure\": 1016.3,\r\n"
							+ "            \"cloudcover\": 77.1,\r\n"
							+ "            \"visibility\": 8.8,\r\n"
							+ "            \"solarradiation\": 77.9,\r\n"
							+ "            \"solarenergy\": 6.6,\r\n"
							+ "            \"uvindex\": 4.0,\r\n"
							+ "            \"severerisk\": 10.0,\r\n"
							+ "            \"sunrise\": \"07:34:25\",\r\n"
							+ "            \"sunsetEpoch\": 0,\r\n"
							+ "            \"moonphase\": 0.79,\r\n"
							+ "            \"conditions\": \"Partially cloudy\",\r\n"
							+ "            \"description\": \"Partly cloudy throughout the day.\",\r\n"
							+ "            \"icon\": \"partly-cloudy-day\",\r\n"
							+ "            \"hours\": null\r\n"
							+ "        }\r\n"
							+ "    ]\r\n"
							+ "}") })) })
	@GetMapping("/daily/{city}/{state}/{startDate}/{endDate}")
	public ResponseEntity<Object> getDailyWeather(@PathVariable String city, @PathVariable String state, @PathVariable String startDate, @PathVariable String endDate) throws Exception{
		return new ResponseEntity<>(visualCrossingWeatherService.makeApiCall(OutputSection.DAILY, city, state, startDate, endDate), HttpStatus.OK);
	}
	
	@Operation(summary = "Get the Current weather data", description = "Get the Current weather data for a specified location in a given date range", responses = {
			@ApiResponse(description = "Success", responseCode = "200", content = @Content(schema = @Schema(implementation = WeatherResponse.class), examples = {
					@ExampleObject(value = "{\r\n"
							+ "    \"resolvedAddress\": \"Lima, OH, United States\",\r\n"
							+ "    \"address\": \"Lima, OH\",\r\n"
							+ "    \"timezone\": \"America/New_York\",\r\n"
							+ "    \"days\": [\r\n"
							+ "        {\r\n"
							+ "            \"datetime\": \"2024-11-24\",\r\n"
							+ "            \"datetimeEpoch\": 1732424400,\r\n"
							+ "            \"tempmax\": 47.1,\r\n"
							+ "            \"tempmin\": 37.2,\r\n"
							+ "            \"temp\": 41.0,\r\n"
							+ "            \"feelslikemax\": 44.2,\r\n"
							+ "            \"feelslikemin\": 30.1,\r\n"
							+ "            \"feelslike\": 35.8,\r\n"
							+ "            \"dew\": 35.4,\r\n"
							+ "            \"humidity\": 80.6,\r\n"
							+ "            \"precip\": 0.0,\r\n"
							+ "            \"precipprob\": 3.0,\r\n"
							+ "            \"precipcover\": 0.0,\r\n"
							+ "            \"preciptype\": null,\r\n"
							+ "            \"now\": 0.0,\r\n"
							+ "            \"windgust\": 18.3,\r\n"
							+ "            \"windspeed\": 10.3,\r\n"
							+ "            \"winddir\": 206.8,\r\n"
							+ "            \"pressure\": 1016.4,\r\n"
							+ "            \"cloudcover\": 74.8,\r\n"
							+ "            \"visibility\": 8.8,\r\n"
							+ "            \"solarradiation\": 80.1,\r\n"
							+ "            \"solarenergy\": 6.8,\r\n"
							+ "            \"uvindex\": 4.0,\r\n"
							+ "            \"severerisk\": 10.0,\r\n"
							+ "            \"sunrise\": \"07:34:25\",\r\n"
							+ "            \"sunsetEpoch\": 1732486320,\r\n"
							+ "            \"moonphase\": 0.79,\r\n"
							+ "            \"conditions\": \"Partially cloudy\",\r\n"
							+ "            \"description\": \"Partly cloudy throughout the day.\",\r\n"
							+ "            \"icon\": \"partly-cloudy-day\",\r\n"
							+ "            \"hours\": null\r\n"
							+ "        }\r\n"
							+ "    ]\r\n"
							+ "}") })) })
	@GetMapping("/current/{city}/{state}/{startDate}/{endDate}")
	public ResponseEntity<Object> getCurrentWeather(@PathVariable String city, @PathVariable String state, @PathVariable String startDate, @PathVariable String endDate) throws Exception{
		return new ResponseEntity<>(visualCrossingWeatherService.makeApiCall(OutputSection.CURRENT, city, state, startDate, endDate), HttpStatus.OK);
	}
}
